#!/bin/bash

export DOTFILES_DIR EXTRA_DIR
DOTFILES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"


# Install packages
sudo apt-get update
sudo apt-get install -y vim \
	tmux\
    software-properties-common

# Install RVM
sudo apt-add-repository -y ppa:rael-gc/rvm
sudo apt-get update
sudo apt-get install -y rvm
source "/etc/profile.d/rvm.sh"
rvm install ruby

# Install YADR
sh -c "`curl -fsSL https://raw.githubusercontent.com/skwp/dotfiles/master/install.sh`"

ln -sfv "$DOTFILES_DIR/system/.tmux.conf" ~
ln -sfv "$DOTFILES_DIR/system/.aliases" ~
ln -sfv "$DOTFILES_DIR/system/.vimrc" ~
ln -sfv "$DOTFILES_DIR/system/.vim" ~
